version: '3'

services:

  patient:
    image: asushares/patient:latest
    deploy:
      replicas: 1
      resources:
        reservations:
          memory: 16M
        limits:
          memory: 64M
    restart: unless-stopped
    ports:
      - 4200:80
    depends_on:
      - hapi
    environment:
      - PATIENT_PORTAL_DEFAULT_FHIR_URL=http://localhost:8080/fhir
      - PATIENT_PORTAL_CONSENT_CDS_ROOT_URL=http://localhost:3000


  consent-manager:
    image: asushares/provider:latest
    deploy:
      replicas: 1
      resources:
        reservations:
          memory: 16M
        limits:
          memory: 64M
    restart: unless-stopped
    ports:
      - 4201:80
    depends_on:
      - hapi
    environment:
      - PROVIDER_DEFAULT_FHIR_URL=http://localhost:8080/fhir

  rules:
    image: asushares/rules:latest
    deploy:
      replicas: 1
      resources:
        reservations:
          memory: 16M
        limits:
          memory: 64M
    restart: unless-stopped
    ports:
      - 4202:80
    depends_on:
      - consent-manager
      - hapi
    environment:
      - DEFAULT_RULES_FILE_URL=http://localhost:3000/data/sensitivity-rules.json

  cds:
    image: asushares/cds:latest
    deploy:
      replicas: 1
      resources:
        reservations:
          memory: 32M
        limits:
          memory: 256M
      # restart_policy: unless-stopped
    restart: unless-stopped
    ports:
      - 3000:3000
    depends_on:
      - hapi
    environment:
      - FHIR_BASE_URL=http://hapi:8080/fhir
      - ORG_NAME=My CDS Consent Sandbox
      - ORG_URL=https://www.example.com
      - ADMINISTRATOR_PASSWORD=admin

  hapi:
    image: hapiproject/hapi:v6.10.1
    deploy:
      resources:
        reservations:
          memory: 1.5G
        limits:
          memory: 4G
    restart: unless-stopped
    ports:
      - 8080:8080
    depends_on:
      - postgresql
    environment:
      - hapi.fhir.fhir_version=R5
      - hapi.fhir.server_address=http://localhost:8080/fhir
      - spring.datasource.driverClassName=org.postgresql.Driver
      - spring.datasource.username=hapi
      - spring.datasource.password=HAPI-USER-ONLY
      - spring.datasource.url=jdbc:postgresql://postgresql:5432/hapi
      - spring.jpa.properties.hibernate.dialect=ca.uhn.fhir.jpa.model.dialect.HapiFhirPostgres94Dialect
      - spring.jpa.properties.hibernate.search.enabled=false
    volumes:
      - postgresql-data:/var/lib/postgresql/data:rw

  postgresql:
    image: postgres:16-alpine
    deploy:
      replicas: 1
      resources:
        reservations:
          memory: 128M
    restart: unless-stopped
    environment:
      - POSTGRES_USER=hapi
      - POSTGRES_PASSWORD=HAPI-USER-ONLY
      - POSTGRES_DB=hapi

volumes:
  postgresql-data: