version: '3'

services:
  cds:
    image: asushares/cds:latest
    deploy:
      replicas: 1
      resources:
        reservations:
          memory: 64M
      # restart_policy: unless-stopped
    restart: unless-stopped
    ports:
      - 3000:3000
    depends_on:
      - hapi
    environment:
      - FHIR_BASE_URL=http://hapi:8080/fhir
      - ORG_NAME=My CDS Consent Sandbox
      - ORG_URL=https://www.example.com


  consent-manager:
    image: asushares/consent-manager:latest
    deploy:
      replicas: 1
      resources:
        reservations:
          memory: 64M
    restart: unless-stopped
    ports:
      - 4200:80
    depends_on:
      - hapi
    environment:
      - CONSENT_BUILDER_DEFAULT_FHIR_URL=http://localhost:8080/fhir

  hapi:
    image: hapiproject/hapi:v6.8.3
    deploy:
      resources:
        reservations:
          memory: 1.5G
        limits:
          memory: 4G
    restart: unless-stopped
    ports:
      - 8080:8080
    depends_on:
      - postgresql
    environment:
      - hapi.fhir.fhir_version=R5
      - hapi.fhir.server_address=http://localhost:8080/fhir
      - spring.datasource.driverClassName=org.postgresql.Driver
      - spring.datasource.username=hapi
      - spring.datasource.password=HAPI-USER-ONLY
      - spring.datasource.url=jdbc:postgresql://postgresql:5432/hapi
      - spring.jpa.properties.hibernate.dialect=ca.uhn.fhir.jpa.model.dialect.HapiFhirPostgres94Dialect
      - spring.jpa.properties.hibernate.search.enabled=false
    volumes:
      - postgresql-data:/var/lib/postgresql/data:rw
  postgresql:
    image: postgres:16-alpine
    deploy:
      replicas: 1
      resources:
        reservations:
          memory: 128M
    restart: unless-stopped
    environment:
      - POSTGRES_USER=hapi
      - POSTGRES_PASSWORD=HAPI-USER-ONLY
      - POSTGRES_DB=hapi

volumes:
  postgresql-data: